update 2.1

diff --git a/trunk/oops-firewall b/trunk/oops-firewall
--- a/trunk/oops-firewall
+++ b/trunk/oops-firewall
@@ -1,5 +1,7 @@
 #!/bin/sh
 #
+# $Id: oops-firewall,v 1.2 2004-08-04 14:30:33 oops Exp $
+#
 # OOPS Firewall 네트워크 서버 방화벽 설정 2.0
 # 작성 : 김정균 http://www.oops.org
 # 날짜 : 2003.03.21
@@ -59,150 +61,251 @@ ETH1_IPADDR=`/sbin/ifconfig eth1 2> /dev/null | grep 'inet addr' | awk '{print $
 ETH1_SUBNET=`/sbin/ifconfig eth1 2> /dev/null | grep 'inet addr' | awk '{print $4}' | sed -e 's/.*://'`
 ETH1_NET=`route -n | grep -w U | grep eth1 | awk '{print $1}'`
 
+
 # 설정 파일을 불러들임
-. /etc/oops_firewall/oops_firewall.conf
+. /etc/oops_firewall/filter.conf
+. /etc/oops_firewall/masq.conf
+. /etc/oops_firewall/forward.conf
 
-##############################################################################
-# GLOBAL 설정
-##############################################################################
 
-# IP forwarding 을 가능하게
-# 이 설정은 나중 FORWARD 규칙이 추가될때를 대비해 미리 설정
-# echo 1 > /proc/sys/net/ipv4/ip_forward
+if [ "$1" = "" ]; then
 
-# TCP Syncookies 를 사용할수 있게 하기 위해
-echo 1 > /proc/sys/net/ipv4/tcp_syncookies
+  ##############################################################################
+  # GLOBAL 설정
+  ##############################################################################
 
-# RFC1812에 따른 IP spoof 방지를 위한 설정(커널 2.2 이상 버전)
-# 아래에서 ip 스푸핑 해당 항목 참고
-for pfile in /proc/sys/net/ipv4/conf/*/rp_filter
-do
-  echo 1 > $pfile
-done
+  # 서비스를 시작하기전 초기화
+  iptables -P INPUT ACCEPT
+  iptables -F INPUT
+  iptables -t nat -P PREROUTING ACCEPT
+  iptables -t nat -F PREROUTING
+  iptables -t nat -P POSTROUTING ACCEPT
+  iptables -t nat -F POSTROUTING
+  echo 0 > /proc/sys/net/ipv4/ip_forward
 
-# ip 주소를 스푸핑한다고 예상되는 경우 로그에 기록하기
+  # TCP Syncookies 를 사용할수 있게 하기 위해
+  echo 1 > /proc/sys/net/ipv4/tcp_syncookies
 
-echo 1 > /proc/sys/net/ipv4/conf/all/log_martians
+  # RFC1812에 따른 IP spoof 방지를 위한 설정(커널 2.2 이상 버전)
+  # 아래에서 ip 스푸핑 해당 항목 참고
+  for pfile in /proc/sys/net/ipv4/conf/*/rp_filter
+  do
+    echo 1 > $pfile
+  done
 
-# 브로드캐스트, 멀티캐스트 주소에 ICMP 메시지 보내는것 막기
-# "smurf" 공격 방지용
-# 아래에서 해당 조항 참고
-# 커널 2.2 이상에 해당
+  # 정의되지 않은 에러 메시지를 막음
+  echo 1 > /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses
 
-echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
+  # ip 주소를 스푸핑한다고 예상되는 경우 로그에 기록하기
 
-# 모든 서비스를 허가
-${IPTABLES} -A INPUT -i lo -j ACCEPT
+  echo 1 > /proc/sys/net/ipv4/conf/all/log_martians
 
-if [ "${ALLOWSELF}" = "1" ]; then
-  echo "${IPTABLES} -A INPUT -s ${ETH0_NET}/${ETH0_SUBNET} -j ACCEPT"
-  ${IPTABLES} -A INPUT -s ${ETH0_NET}/${ETH0_SUBNET} -j ACCEPT
-  if [ "${ETH1_IPADDR}" != "" ]; then
-    echo "${IPTABLES} -A INPUT -s ${ETH1_NET}/${ETH1_SUBNET} -j ACCEPT"
-    ${IPTABLES} -A INPUT -s ${ETH1_NET}/${ETH1_SUBNET} -j ACCEPT
+  # 브로드캐스트, 멀티캐스트 주소에 ICMP 메시지 보내는것 막기
+  # "smurf" 공격 방지용
+  # 아래에서 해당 조항 참고
+  # 커널 2.2 이상에 해당
+
+  echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
+
+  # 모든 서비스를 허가
+  ${IPTABLES} -A INPUT -i lo -j ACCEPT
+
+  if [ "${ALLOWSELF}" = "1" ]; then
+    echo "${IPTABLES} -A INPUT -s ${ETH0_NET}/${ETH0_SUBNET} -j ACCEPT"
+    ${IPTABLES} -A INPUT -s ${ETH0_NET}/${ETH0_SUBNET} -j ACCEPT
+    if [ "${ETH1_NET}" != "" ]; then
+      echo "${IPTABLES} -A INPUT -s ${ETH1_NET}/${ETH1_SUBNET} -j ACCEPT"
+      ${IPTABLES} -A INPUT -s ${ETH1_NET}/${ETH1_SUBNET} -j ACCEPT
+    fi
+  else
+    echo "${IPTABLES} -A INPUT -s ${ETH0_IPADDR} -j ACCEPT"
+    ${IPTABLES} -A INPUT -s ${ETH0_IPADDR} -j ACCEPT
+    if [ "${ETH1_IPADDR}" != "" ]; then
+      echo "${IPTABLES} -A INPUT -s ${ETH1_IPADDR} -j ACCEPT"
+      ${IPTABLES} -A INPUT -s ${ETH1_IPADDR} -j ACCEPT
+    fi
   fi
-else
-  echo "${IPTABLES} -A INPUT -s ${ETH0_IPADDR} -j ACCEPT"
-  ${IPTABLES} -A INPUT -s ${ETH0_IPADDR} -j ACCEPT
-  if [ "${ETH1_IPADDR}" != "" ]; then
-    echo "${IPTABLES} -A INPUT -s ${ETH1_IPADDR} -j ACCEPT"
-    ${IPTABLES} -A INPUT -s ${ETH1_IPADDR} -j ACCEPT
+
+  if [ "${ALLOWALL}" != "" ] ; then
+    for values in ${ALLOWALL}
+    do
+      echo "${IPTABLES} -A INPUT -s ${values} -j ACCEPT"
+      ${IPTABLES} -A INPUT -s ${values} -j ACCEPT
+    done
   fi
-fi
 
-if [ "${ALLOWALL}" != "" ] ; then
-  for values in ${ALLOWALL}
-  do
-    echo "${IPTABLES} -A INPUT -s ${values} -j ACCEPT"
-    ${IPTABLES} -A INPUT -s ${values} -j ACCEPT
-  done
-fi
+  ##############################################################################
+  # TCP 설정
+  ##############################################################################
 
-##############################################################################
-# TCP 설정
-##############################################################################
+  # 모든 곳으로의 포트를 open
+  if [ "${TCP_ALLOWPORT}" != "" ]; then
+    for values in ${TCP_ALLOWPORT}
+    do
+      echo "${IPTABLES} -A INPUT -p tcp --dport ${values} -j ACCEPT"
+      ${IPTABLES} -A INPUT -p tcp --dport ${values} -j ACCEPT
+    done
+  fi
 
-# 모든 곳으로의 포트를 open
-if [ "${TCP_ALLOWPORT}" != "" ]; then
-  for values in ${TCP_ALLOWPORT}
-  do
-    echo "${IPTABLES} -A INPUT -p tcp --dport ${values} -j ACCEPT"
-    ${IPTABLES} -A INPUT -p tcp --dport ${values} -j ACCEPT
-  done
-fi
+  # 특정 호스트로의 포트를 open
 
-# 특정 호스트로의 포트를 open
+  if [ "${TCP_HOSTPERPORT}" != "" ]; then
+    for values in ${TCP_HOSTPERPORT}
+    do
+      echo ${values} | {
+        IFS=':' read hosts ports
+        echo "${IPTABLES} -A INPUT -s ${hosts} -p tcp --dport ${ports} -j ACCEPT"
+        ${IPTABLES} -A INPUT -s ${hosts} -p tcp --dport ${ports} -j ACCEPT
+      }
+    done
+  fi
 
-if [ "${TCP_HOSTPERPORT}" != "" ]; then
-  for values in ${TCP_HOSTPERPORT}
-  do
-    echo ${values} | {
-      IFS=':' read hosts ports
-      echo "${IPTABLES} -A INPUT -s ${hosts} -p tcp --dport ${ports} -j ACCEPT"
-      ${IPTABLES} -A INPUT -s ${hosts} -p tcp --dport ${ports} -j ACCEPT
-    }
-  done
-fi
+  ##############################################################################
+  # UDP 설정
+  ##############################################################################
 
-##############################################################################
-# UDP 설정
-##############################################################################
-
-# 모든 곳으로의 포트를 open
-if [ "${UDP_ALLOWPORT}" != "" ]; then
-  for values in ${UDP_ALLOWPORT}
-  do
-    echo "${IPTABLES} -A INPUT -p udp --dport ${values} -j ACCEPT"
-    ${IPTABLES} -A INPUT -p udp --dport ${values} -j ACCEPT
-  done
-fi  
+  # 모든 곳으로의 포트를 open
+  if [ "${UDP_ALLOWPORT}" != "" ]; then
+    for values in ${UDP_ALLOWPORT}
+    do
+      echo "${IPTABLES} -A INPUT -p udp --dport ${values} -j ACCEPT"
+      ${IPTABLES} -A INPUT -p udp --dport ${values} -j ACCEPT
+    done
+  fi  
   
-# 특정 호스트로의 포트를 open
+  # 특정 호스트로의 포트를 open
 
-if [ "${UDP_HOSTPERPORT}" != "" ]; then
-  for values in ${UDP_HOSTPERPORT}
-  do
-    echo ${values} | {
-      IFS=':' read hosts ports
-      echo "${IPTABLES} -A INPUT -s ${hosts} -p udp --dport ${ports} -j ACCEPT"
-      ${IPTABLES} -A INPUT -s ${hosts} -p udp --dport ${ports} -j ACCEPT
-    }
-  done
+  if [ "${UDP_HOSTPERPORT}" != "" ]; then
+    for values in ${UDP_HOSTPERPORT}
+    do
+      echo ${values} | {
+        IFS=':' read hosts ports
+        echo "${IPTABLES} -A INPUT -s ${hosts} -p udp --dport ${ports} -j ACCEPT"
+        ${IPTABLES} -A INPUT -s ${hosts} -p udp --dport ${ports} -j ACCEPT
+      }
+    done
+  fi
+
+  ##############################################################################
+  # ICMP 설정
+  ##############################################################################
+
+  # 특정 호스트에 ping 을 열어줄때
+  if [ "${ICMP_HOSTPERPING}" != "" ]; then
+    for values in ${ICMP_HOSTPERPING}
+    do
+      echo "${IPTABLES} -A INPUT -s ${values} -p icmp --icmp-type echo-request -j ACCEPT"
+      ${IPTABLES} -A INPUT -s ${values} -p icmp --icmp-type echo-request -j ACCEPT
+    done
+  fi
+
+  ##############################################################################
+  # DENY 정책
+  ##############################################################################
+
+  # 모든 서비스를 거부
+  if [ "${TCP_DENYPORT}" != "" ]; then
+    echo "${IPTABLES} -A INPUT -d ${ETH0_IPADDR} -p tcp --syn -j DROP"
+    ${IPTABLES} -A INPUT -d ${ETH0_IPADDR} -p tcp --syn -j REJECT
+    echo "${IPTABLES} -A INPUT -p tcp --dport 1:${TCP_DENYPORT} -j DROP"
+    ${IPTABLES} -A INPUT -p tcp --dport 1:${TCP_DENYPORT} -j DROP
+  fi
+  if [ "${UDP_DENYPORT}" != "" ]; then
+    echo "${IPTABLES} -A INPUT -p udp --dport 1:${UDP_DENYPORT} -j DROP"
+    ${IPTABLES} -A INPUT -p udp --dport 1:${UDP_DENYPORT} -j DROP
+  fi
+  echo "${IPTABLES} -A INPUT -p icmp --icmp-type echo-request -j REJECT"
+  ${IPTABLES} -A INPUT -p icmp --icmp-type echo-request -j REJECT
+
+  # 어떤 이유로 확인할수 없는 패킷들을 drop 시킴
+  echo "${IPTABLES} -A INPUT -m state --state INVALID -j DROP"
+  ${IPTABLES} -A INPUT -m state --state INVALID -j DROP
+
+
+  ##############################################################################
+  # Masqurade Rule
+  ##############################################################################
+
+  # 주의사항
+  # masq client 에서 외부의 dns 를 설정하기 위해서는 위의 TCP_ALLPROT 와
+  # UDT_ALLPORT 에 53번을 지정해 줘야 함
+
+  if [ "${MASQ_USED}" = "yes" ]; then
+    if [ "${MASQ_DEVICE}" = "eth0" ] || [ "${MASQ_DEVICE}" = "eth1" ]; then
+      if [ "${MASQ_DEVICE}" = "eth0" ]; then
+        MASQ_ADDR="${ETH0_IPADDR}"
+      elif [ "${MASQ_DEVICE}" = "eth1" ]; then
+        MASQ_ADDR="${ETH1_IPADDR}"
+      fi
+      # packet forwarding 을 가능하게 함
+      echo 1 > /proc/sys/net/ipv4/ip_forward
+
+      echo "${IPTABLES} -t nat -A POSTROUTING -o ${MASQ_DEVICE} -j SNAT --to ${MASQ_ADDR}"
+      ${IPTABLES} -t nat -A POSTROUTING -o ${MASQ_DEVICE} -j SNAT --to ${MASQ_ADDR}
+
+      # dial pad 를 사용하기 위한 설정
+      if [ "${MASQ_DIAL}" != "" ]; then
+        for value in ${MASQ_DIAL}
+        do
+          echo "${IPTABLES} -t nat -A PREROUTING -p tcp --dport 51210 -j DNAT --to ${value}:51210"
+          ${IPTABLES} -t nat -A PREROUTING -p tcp --dport 51210 -j DNAT --to ${value}:51210
+          echo "${IPTABLES} -t nat -A PREROUTING -p udp --dport 51200 -j DNAT --to ${value}:51200"
+          ${IPTABLES} -t nat -A PREROUTING -p udp --dport 51200 -j DNAT --to ${value}:51200
+          echo "${IPTABLES} -t nat -A PREROUTING -p udp --dport 51201 -j DNAT --to ${value}:51201"
+          ${IPTABLES} -t nat -A PREROUTING -p udp --dport 51201 -j DNAT --to ${value}:51201
+        done
+      fi
+    else
+      echo "Ethernet Device 는 eth1 까지만 지원합니다."
+      echo "방화벽 설정을 초기화 합니다."
+      iptables -P INPUT ACCEPT
+      iptables -F INPUT
+      iptables -t nat -P POSTROUTING ACCEPT
+      iptables -t nat -F POSTROUTING
+      echo 0 > /proc/sys/net/ipv4/ip_forward
+      exit 1
+    fi
+  fi
+
+  ##############################################################################
+  # Forwarding Rule
+  ##############################################################################
+
+  # masq device 가 존재할 경우 즉 ethernet device 가 여러개일 경우
+  # msql device 로 지정된 device 의 주소를 외부로 나갈 주소로 지정
+  #
+  if [ "${MASQ_DEVICE}" = "" ]; then
+    INCOM_ADDR=${ETH0_IPADDR}
+  else
+    INCOM_ADDR=${MASQ_ADDR}
+  fi
+
+  if [ "${TCP_FORWARD_TO}" != "" ]; then
+    for values in ${TCP_FORWARD_TO}
+    do
+      echo ${values} | {
+        IFS=':' read lports raddr rports
+        echo "${IPTABLES} -t nat -A PREROUTING -p tcp -d ${INCOM_ADDR} --dport ${lports} -j DNAT --to ${raddr}:${rports}"
+        ${IPTABLES} -t nat -A PREROUTING -p tcp -d ${INCOM_ADDR} --dport ${lports} -j DNAT --to ${raddr}:${rports}
+      }
+    done
+  fi
+
+  if [ "${UDP_FORWARD_TO}" != "" ]; then
+    for values in ${UDP_FORWARD_TO}
+    do
+      echo ${values} | {
+        IFS=':' read lports raddr rports
+        echo "${IPTABLES} -t nat -A PREROUTING -p tcp -d ${INCOM_ADDR} --dport ${lports} -j DNAT --to ${raddr}:${rports}"
+        ${IPTABLES} -t nat -A PREROUTING -p tcp -d ${INCOM_ADDR} --dport ${lports} -j DNAT --to ${raddr}:${rports}
+      }
+    done
+  fi
+elif [ "$1" = "-v" ];then
+  echo "OOPS FIREWALL v.2.1 by JoungKyun Kim"
+  echo "Copyright by GPL Since 2000-2001"
+else
+  echo "USAGE : $0 [-v]"
+  echo "   -v print version"
 fi
-
-##############################################################################
-# ICMP 설정
-##############################################################################
-
-# 특정 호스트에 ping 을 열어줄때
-if [ "${ICMP_HOSTPERPING}" != "" ]; then
-  for values in ${ICMP_HOSTPERPING}
-  do
-    echo "${IPTABLES} -A INPUT -s ${values} -p icmp --icmp-type echo-request -j ACCEPT"
-    ${IPTABLES} -A INPUT -s ${values} -p icmp --icmp-type echo-request -j ACCEPT
-  done
-fi
-
-##############################################################################
-# DENY 정책
-##############################################################################
-
-# 모든 서비스를 거부
-if [ "${TCP_DENYPORT}" != "" ]; then
-  echo "${IPTABLES} -A INPUT -d ${ETH0_IPADDR} -p tcp --syn -j DROP"
-  ${IPTABLES} -A INPUT -d ${ETH0_IPADDR} -p tcp --syn -j REJECT
-  echo "${IPTABLES} -A INPUT -p tcp --dport 1:${TCP_DENYPORT} -j DROP"
-  ${IPTABLES} -A INPUT -p tcp --dport 1:${TCP_DENYPORT} -j DROP
-fi
-if [ "${UDP_DENYPORT}" != "" ]; then
-  echo "${IPTABLES} -A INPUT -p udp --dport 1:${UDP_DENYPORT} -j DROP"
-  ${IPTABLES} -A INPUT -p udp --dport 1:${UDP_DENYPORT} -j DROP
-fi
-echo "${IPTABLES} -A INPUT -p icmp --icmp-type echo-request -j REJECT"
-${IPTABLES} -A INPUT -p icmp --icmp-type echo-request -j REJECT
-
-# 어떤 이유로 확인할수 없는 패킷들을 drop 시킴
-echo "${IPTABLES} -A INPUT -m state --state INVALID -j DROP"
-${IPTABLES} -A INPUT -m state --state INVALID -j DROP
-
 exit 0
